spring:
  profiles:
    active: development

---

spring:
  config:
    activate:
      on-profile: development

logging:
  level:
    web: INFO

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: production