spring:
  profiles:
    active: development

---

spring:
  config:
    activate:
      on-profile: development
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create

logging:
  level:
    web: INFO

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: production