spring:
  profiles:
    active: development

---

spring:
  config:
    activate:
      on-profile: development

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: production